# file is automatically sourced before any test and makes sure that the functions are available

source("../R/aaa_generics.R")
source("../R/npdeControl.R")
source("../R/NpdeData.R")
source("../R/NpdeSimData.R")
source("../R/NpdeData-methods.R")
source("../R/NpdeRes.R")
source("../R/NpdeRes-methods.R")
source("../R/NpdeObject.R")
source("../R/NpdeObject-methods.R")
source("../R/mainNpde.R")
source("../R/npde.R")
source("../R/plotNpde-methods.R")
source("../R/plotNpde-unitFunctionsAux.R")
source("../R/plotNpde-unitFunctionsRef.R")
source("../R/plotNpde-unitFunctionsPI.R")
source("../R/plotNpde-meanProf.R")
source("../R/plotNpde-plotFunctions.R")
source("../R/compute_distribution.R")
source("../R/compute_pd.R")
source("../R/compute_ploq.R")
source("../R/compute_npde.R")
source("../R/qqplot.R")

