# file is automatically sourced before any test and makes sure that the functions are available
if(!"path"%in%ls()) path="~/../Desktop/npde30/"
source(paste(path,"R/aaa_generics.R",sep=""))
source(paste(path,"R/npdeControl.R",sep=""))
source(paste(path,"R/NpdeData.R",sep=""))
source(paste(path,"R/NpdeSimData.R",sep=""))
source(paste(path,"R/NpdeData-methods.R",sep=""))
source(paste(path,"R/NpdeRes.R",sep=""))
source(paste(path,"R/NpdeRes-methods.R",sep=""))
source(paste(path,"R/NpdeObject.R",sep=""))
source(paste(path,"R/NpdeObject-methods.R",sep=""))
source(paste(path,"R/mainNpde.R",sep=""))
source(paste(path,"R/npde.R",sep=""))
source(paste(path,"R/plotNpde-methods.R",sep=""))
source(paste(path,"R/plotNpde-unitFunctionsAux.R",sep=""))
source(paste(path,"R/plotNpde-unitFunctionsRef.R",sep=""))
source(paste(path,"R/plotNpde-unitFunctionsPI.R",sep=""))
source(paste(path,"R/plotNpde-meanProf.R",sep=""))
source(paste(path,"R/plotNpde-plotFunctions.R",sep=""))
source(paste(path,"R/compute_distribution.R",sep=""))
source(paste(path,"R/compute_pd.R",sep=""))
source(paste(path,"R/compute_ploq.R",sep=""))
source(paste(path,"R/compute_npde.R",sep=""))
source(paste(path,"R/qqplot.R",sep=""))

